const configRoute = {
  home: '/',
  about: '/about',
  contact: '/contact',
  course: '/course',
  learn: '/learn',
  knowledge: '/knowledge',
  event: '/event',
  service: '/service',
  product: '/product',
  cart: '/cart',
  checkout: '/checkout',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  customCourse: '/custom-course',
  setting: {
    profile: '/setting',
    myCourse: '/setting/my-course',
    order: '/setting/order',
    address: '/setting/address',
    payment: '/setting/payment',
    notifications: '/setting/notifications',
    security: '/setting/security',
    childAccount: '/setting/child-account',
    review: '/setting/need-review',
    refund: '/setting/refund'
  },
  profile: '/profile',
  contentCreator: {
    dashboard: '/content-creator/dashboard',
    blog: '/content-creator/blog',
    addBlog: '/content-creator/blog/add',
    editBlog: '/content-creator/blog/edit',
    course: '/content-creator/course',
    addCourse: '/content-creator/course/add',
    editCourse: '/content-creator/course/edit'
  },
  help: '/help/faq',
  kid: {
    dashboard: '/kid',
    course: '/kid/course',
    knowledge: '/kid/knowledge',
    bookmark: '/kid/bookmark',
    game: '/kid/game',
    achievement: '/kid/achievement'
  },
  manager: {
    dashboard: '/manager',
    order: '/manager/order',
    blog: '/manager/blog',
    course: '/manager/course',
    product: '/manager/product',
    report: '/manager/report',
    productNew: '/manager/product/new',
    productEdit: '/manager/product/edit',
    combo: '/manager/combo'
  },
  admin: {
    dashboard: '/admin',
    order: '/admin/order',
    blog: '/admin/blog',
    addBlog: '/admin/blog/add',
    editBlog: '/admin/blog/edit',
    course: '/admin/course',
    addCourse: '/admin/course/add',
    editCourse: '/admin/course/edit',
    product: '/admin/product',
    productNew: '/admin/product/new',
    productEdit: '/admin/product/edit',
    user: '/admin/user',
    report: '/admin/report',
    combo: '/admin/combo'
  },
  salesman: {
    dashboard: '/salesman',
    order: '/salesman/order',
    blog: '/salesman/blog',
    addBlog: '/salesman/blog/add',
    editBlog: '/salesman/blog/edit',
    course: '/salesman/course',
    addCourse: '/salesman/course/add',
    editCourse: '/salesman/course/edit',
    product: '/salesman/product',
    productNew: '/salesman/product/new',
    productEdit: '/salesman/product/edit',
    user: '/salesman/user',
    combo: '/salesman/combo',
    comboNew: '/salesman/combo/new',
    comboEdit: '/salesman/combo/edit'
  },
  support: {
    dashboard: '/support',
    order: '/support/order',
    user: '/support/user',
    refund: '/support/refund',
    exchange: '/support/exchange',
    blog: '/support/blog',
    course: '/support/course',
    settings: '/support/settings',
    tickets: '/support/tickets',
    product: '/support/product',
    chat: '/support/chat',
    report: '/support/report'
  },
  expert: {
    dashboard: '/expert',
    course: '/expert/course'
  }
}

export default configRoute
